name: digital_clock
description: Digital clock.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_clock_helper:
    path: ../flutter_clock_helper
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Economica
      fonts:
        - asset: third_party/economica/Economica-Regular.ttf
        - asset: third_party/economica/Economica-Bold.ttf
          weight: 700
    - family: Bitter
      fonts:
        - asset: third_party/bitter/Bitter-Regular.ttf
        - asset: third_party/bitter/Bitter-Bold.ttf
          weight: 700

  assets:
    - third_party/flare/windy.flr
    - third_party/flare/cloudy_day.flr
    - third_party/flare/cloudy_night.flr
    - third_party/flare/heavy_rainy_day.flr
    - third_party/flare/heavy_rainy_night.flr
    - third_party/flare/thunder_rainy.flr
    - third_party/flare/sunny_day.flr
    - third_party/flare/moon.flr
    - third_party/flare/foggy.flr
    - third_party/flare/snowy.flr
    - third_party/img/sunrise.jpg
    - third_party/img/cloudy.jpg
    - third_party/img/night.jpg
    - third_party/img/sunset.jpg
    - third_party/img/dark.jpg